### ISSUE TITLE
i get this when i run

### ISSUE THREAD

**Issue by qwertyboi16** [Sxvxgee/Discord-AntiPing#1]
C:\Users\luke1\3D Objects\Discord-AntiPing-main>py main.py
Traceback (most recent call last):
  File "C:\Users\luke1\3D Objects\Discord-AntiPing-main\main.py", line 53, in <module>
    bot.run(TOKEN, self_bot = True)
  File "C:\Users\luke1\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 649, in run
    return future.result()
  File "C:\Users\luke1\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\client.py", line 628, in runner
    await self.start(*args, **kwargs)
TypeError: Client.start() got an unexpected keyword argument 'self_bot'

**Comment by Sxvxgee** [comment]
Do you have discord.py-self rebase branch installed, or is it another library that you're using? If you're using another library, uninstall it, and then run the following command: `pip install git+https://github.com/dolfies/discord.py-self@rebase`

**Comment by Sxvxgee** [comment]
I added that to `bot.run` without testing, my bad. I fixed it just now by passing it to the bot constructor. Reinstall the new code and it should work.
